name: Hourly Version Check and Bump Update

on:
  schedule:
    - cron: '0 * * * *' # Every hour. UTC
  workflow_dispatch: 

jobs:
  daily-nix-bump:
    uses: introducingbloats/introducingbloats/.github/workflows/auto-update-flake.yml@main
    permissions:
      contents: write
    secrets: inherit